---
- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Restart Tempo
  systemd:
    name: tempo
    state: restarted

- name: Restart Otel Collector
  systemd:
    name: otel-collector
    state: restarted

# ... (остальные ваши handlers, например, для Loki/Promtail) ...
