---
- name: Create loki user
  user:
    name: loki
    system: yes
    shell: /usr/sbin/nologin
    create_home: no

- name: Create directories for Loki
  file:
    path: "{{ item }}"
    state: directory
    owner: loki
    group: loki
    mode: '0755'
  loop:
    - /etc/loki
    - /var/lib/loki

- name: Download Loki binary
  command: wget -O /tmp/loki-linux-amd64.zip https://github.com/grafana/loki/releases/download/v3.3.2/loki-linux-amd64.zip
  args:
    creates: /tmp/loki-linux-amd64.zip

- name: Install unzip (if needed)
  apt:
    name: unzip
    state: present

- name: Extract Loki binary
  unarchive:
    src: /tmp/loki-linux-amd64.zip
    dest: /tmp
    remote_src: yes

- name: Move Loki binary to /usr/local/bin
  command: mv /tmp/loki-linux-amd64 /usr/local/bin/loki
  args:
    creates: /usr/local/bin/loki

- name: Make Loki binary executable
  file:
    path: /usr/local/bin/loki
    mode: '0755'

- name: Copy Loki config file
  template:
    src: loki-config.yaml.j2
    dest: /etc/loki/local-config.yaml
    owner: loki
    group: loki
    mode: '0644'

- name: Copy Loki systemd service file
  template:
    src: loki.service.j2
    dest: /etc/systemd/system/loki.service
    mode: '0644'

- name: Reload systemd and start Loki
  systemd:
    daemon_reload: yes
    name: loki
    enabled: yes
    state: started